version: '3.4'

services:
  api:
    build:  &default-build
      context: .
    environment: &environment
      - DATABASE_URL=mysql+pymysql://root:example@db/crms
      - DEBUG=1
    ports:
      - 8080:8080
    env_file:
      - .env
    volumes: &app_volumes
    - .:/app
    depends_on:
      - db
    command: api
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=crms

  adminer:
    image: adminer
    restart: always
    ports:
      - 8085:8080
    depends_on:
      - db
