"""empty message

Revision ID: 00c7a1faf961
Revises: 0d15f9e1b910
Create Date: 2023-05-07 22:18:11.411794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00c7a1faf961'
down_revision = '0d15f9e1b910'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arrow', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('day', schema=None) as batch_op:
        batch_op.drop_column('arrow')

    # ### end Alembic commands ###
