"""empty message

Revision ID: 82ba29b26759
Revises: d7fc55edd316
Create Date: 2023-07-22 09:14:13.469953

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "82ba29b26759"
down_revision = "d7fc55edd316"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("day", schema=None) as batch_op:
        batch_op.drop_index("date")
        batch_op.create_unique_constraint(
            "unique_date_per_user_id", ["date", "user_id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("day", schema=None) as batch_op:
        batch_op.drop_constraint("unique_date_per_user_id", type_="unique")
        batch_op.create_index("date", ["date"], unique=False)

    # ### end Alembic commands ###
