"""empty message

Revision ID: d7fc55edd316
Revises: 00c7a1faf961
Create Date: 2023-05-07 22:23:17.345701

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d7fc55edd316"
down_revision = "00c7a1faf961"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("day_history", schema=None) as batch_op:
        batch_op.add_column(sa.Column("arrow", sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("day_history", schema=None) as batch_op:
        batch_op.drop_column("arrow")

    # ### end Alembic commands ###
